// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NetTestX.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "NetTestX.b68ae9dc-954c-4cdf-8bc4-ca14fc16cb2b";
        public const string Name = "NetTestX";
        public const string Description = @"Unit test scaffolder for .NET";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Mykyta Kovalenko";
        public const string Tags = "";
    }
}
