// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NetTestX.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "NetTestX.VSIX.b68ae9dc-954c-4cdf-8bc4-ca14fc16cb2a";
        public const string Name = "NetTestX.VSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Никита Коваленко";
        public const string Tags = "";
    }
}
