// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NetTestX.VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NetTestXString = "57856323-0846-4a1a-a846-ff1b5efe0129";
        public static Guid NetTestX = new Guid(NetTestXString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GenerateTestsMenuGroup = 0x0001;
        public const int GenerateTestProjectMenuGroup = 0x0002;
        public const int GenerateTestsCommand = 0x1000;
        public const int GenerateTestProjectCommand = 0x2000;
    }
}